[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.0.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "v0.14.1"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "v0.12.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  revision = "v0.30.2"

[[override]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "=v0.32.0"

## deps without releases:

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

[[override]]
  branch = "develop"
  name = "github.com/terra-project/terra"

## transitive deps, with releases:

[[override]]
  name = "github.com/davecgh/go-spew"
  version = "=v1.1.0"

## transitive deps, without releases:

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "c4c61651e9e37fa117f53c5a906d3b63090d8445"

[[override]]
  name = "golang.org/x/sys"
  revision = "4e1fef5609515ec7a2cee7b5de30ba6d9b438cbf"

[[override]]
  name = "google.golang.org/genproto"
  revision = "383e8b2c3b9e36c4076b235b32537292176bae20"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
      name = "github.com/zondax/hid"
      unused-packages = false
